import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de-CH" className="scroll-smooth">
      <body
        className={`w-screen h-screen text-text_primary text-body_mobile xl:text-body_desktop font-quicksand `}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
